#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
IZIN=$( curl https://raw.githubusercontent.com/xkjdox/rijrekeksdpdolwoqkqkakodix/main/Nxbdjekkwso.txt | grep $MYIP )
if [ $MYIP = $IZIN ]; then
echo -e "${green}Permission Accepted${NC}"
else
echo -e "${red}Permission Denied!${NC}";
echo "Only For Premium Users"
exit 0
fi
DOMAIN=$(cat /etc/v2ray/domain);
clear
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (hari): " masaaktif

IP=$(wget -qO- ipinfo.io/ip);
ssl="$(cat ~/log-install.txt | grep -w "Stunnel4" | cut -d: -f2)"
sqd="$(cat ~/log-install.txt | grep -w "Squid" | cut -d: -f2)"
ovpn="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
ovpn2="$(netstat -nlpu | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
sleep 1
echo Ping Host
echo Cek Hak Akses...
sleep 0.5
echo Permission Accepted
clear
sleep 0.5
echo Membuat Akun: $Login
sleep 0.5
echo Setting Password: $Pass
sleep 0.5
clear
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo -e "=========================="
echo -e "INFORMASI PREMIUM"
echo -e "SSH & OVPN ACCOUNT"
echo -e "==========================="
echo -e "IP-Addres : $IP"
echo -e "Hostname : $DOMAIN"
echo -e "Username : $Login "
echo -e "Password : $Pass"
echo -e "=========================="
echo -e "Port openssh : 22"
echo -e "Port dropbear : 109, 143"
echo -e "Port stunnel : $ssl"
echo -e "Port ssh websocket http : 2052"
echo -e "Port ssh websocket https : 443"
echo -e "Port ovpn websocket : 6060"
echo -e "Port ohp ssh : 1414"
echo -e "Port ohp dropbear : 1313"
echo -e "Port ohp ovpn : 1212"
echo -e "Port squid : $sqd"
echo -e "Port badvpn/udpgw : 7100-7300"
echo -e "=========================="
echo -e "Payload Websocket : GET / HTTP/1.1[crlf]Host: $DOMAIN[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "=========================="
echo -e "OpenVPN : OHP 6060 http://$IP:81/tcp-ohp.ovpn"
echo -e "OpenVPN : TCP $ovpn http://$IP:81/client-tcp-$ovpn.ovpn"
echo -e "OpenVPN : UDP $ovpn2 http://$IP:81/client-udp-$ovpn2.ovpn"
echo -e "OpenVPN : SSL 442 http://$IP:81/client-tcp-ssl.ovpn"
echo -e "==========================="
echo -e "Expired on : $exp"
